version: "3"

services:
  app:
    image: sravya98/scm2
    ports:
      - 80:8102
     
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
   
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9092:9092
  
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    depends_on:
      - zookeeper
   

  sockets:
    image: sokser:latest
    ports:
      - 12345:12345
   
  producer:
       
    image: prodk:latest
    depends_on:
      - kafka
      
  consumer:
   
    image: consk:latest

    depends_on:
      - kafka
      
